# Generated by Django 5.2 on 2025-05-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('service', models.CharField(max_length=50)),
                ('service_date', models.DateField(blank=True)),
                ('project_details', models.TextField(blank=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
